repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        args: ["--preview", "--line-length", "79"]
        stages: [commit,push]
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus, --add-import, 'from __future__ import annotations']
        stages: [commit,push]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [ --remove-all-unused-imports, --in-place ]
  - repo: https://github.com/Tesla2000/suppress-lenght-check-import
    rev: '0.1.1'
    hooks:
      - id: add-noqa-to-import
        stages: [commit,push]
  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        stages: [commit,push]
        args: [ --ignore=E203 ]
  - repo: local
    hooks:
      - id: repo-agent
        stages: [push]
        name: RepoAgent
        entry: sh document.sh
        language: system
        pass_filenames: false
        types: [ python ]
        args: [--markdown-docs-path, docs, --language, English, --target-repo-path, .]
